Revert "types: fix misspelling of TPM2_PT_TPM2_HR_PERSISTENT"
We got a compile error with tpm2-tss 2.3.3 in meta-secure-core layer
because this typo wasn't fixed in 2.3.x.
See: https://github.com/tpm2-software/tpm2-tss/issues/1500

Fixes:
capability.c: In function 'capability_read_public':
capability.c:53:44: error: 'TPM2_PT_HR_PERSISTENT' undeclared (first use in this function); did you mean 'TPM2_HR_PERSISTENT'?
   53 |                                            TPM2_PT_HR_PERSISTENT, &more_data,
      |                                            ^~~~~~~~~~~~~~~~~~~~~
      |                                            TPM2_HR_PERSISTENT
capability.c:53:44: note: each undeclared identifier is reported only once for each function it appears in

This reverts commit 888c46c8279a390f2fca7284443ce5fbe35d18db.

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>